version: '3'

services:
  angular-app:
    build:
      context: ./angular-app
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "80:80"
    env_file:
      - .env

  spring-boot-app:
    build:
      context: ./spring-boot-app
      dockerfile: Dockerfile
    container_name: spring-boot-app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/proxibanquev4
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: 'postgres:16-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=proxibanquev4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
