version: '3'

services:
  app:
    image: proxibanque-spring-boot:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    env_file:
      - .env  # Use the .env file for environment variables
    ports:
      - "8080:8080"

  db:
    image: 'postgres:16-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=proxibanquev4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
